version: "1"
volumes:
  node_modules:
services:
  wine-dev:
    build:
      context: ../frontend/
      dockerfile: ../docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ../frontend:/src
      - node_modules:/src/node_modules
